# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=50)),
                ('result', models.TextField(blank=True)),
            ],
        ),
    ]
